//
//  grocerySentences.swift
//  memu-app
//
//  Created by David on 13/5/2024.
//

import Foundation

//let grocerySentences = [
//    "Fresh fruits and vegetables are stocked every morning!",
//    "Don't miss out on our weekend bakery specials.",
//    "Explore our selection of international cheeses and wines.",
//    "Remember to redeem your loyalty points on your next visit.",
//    "Check out the organic section for the latest health foods.",
//    "Our deli offers freshly sliced meats and cheeses daily.",
//    "Join us for our monthly wine tasting events.",
//    "Fresh seafood arrives every Thursday afternoon.",
//    "Look for our gluten-free products throughout the store.",
//    "New vegan options are now available in the frozen section.",
//    "Our floral department has bouquets for every occasion.",
//    "Daily discounts on select items just for you!",
//    "We now carry a range of locally brewed beers.",
//    "Find savings with our store-brand products.",
//    "Our friendly staff is here to help with all your shopping needs.",
//    "We support local farmers by stocking their fresh produce.",
//    "Have you tried our store-made salsa? It's a customer favorite!",
//    "Shop with us and enjoy our clean and organized aisles.",
//    "Download our app for exclusive digital coupons.",
//    "Ask about our catering services for your next event.",
//    "Visit our bakery for custom cake designs.",
//    "Our store is committed to sustainability and green practices.",
//    "We offer a wide selection of organic baby foods.",
//    "Try our freshly brewed coffee at the café corner.",
//    "Need dinner ideas? Pick up one of our ready-to-cook meal kits.",
//    "Check the end of aisles for clearance items and great deals.",
//    "Our store-brand cereals are both delicious and affordable.",
//    "Sign up for our newsletter to receive weekly specials.",
//    "We have ample parking and clean facilities.",
//    "Our pharmacy can fill your prescriptions while you shop.",
//    "Enjoy our selection of fresh and healthy smoothies.",
//    "We feature products from around the world in our international aisle.",
//    "Our loyalty program members get early access to sales.",
//    "Discover new recipes at our cooking demonstrations.",
//    "Kids love our free fruit snack program!",
//    "Pick up a loyalty card today and start saving immediately.",
//    "Our rotisserie chickens are perfect for a quick and easy dinner.",
//    "Find all your pet food needs in our comprehensive pet section.",
//    "We offer a 100% satisfaction guarantee on all our products.",
//    "Look for our weekly flyer in your mailbox or online.",
//    "Stay hydrated with our wide range of bottled waters and beverages.",
//    "Explore our bulk foods section for great deals on staples.",
//    "Our seasonal aisle features unique items for every holiday.",
//    "We provide special shopping hours for seniors and vulnerable shoppers.",
//    "Join our community support programs and make a difference.",
//    "Our meat department features premium cuts and expert advice.",
//    "Shop our exclusive brands for unique products and great value.",
//    "We are open late for your convenience.",
//    "Thank you for choosing us as your trusted grocery partner.",
//    "All major credit cards and digital payments are accepted here."
//]

let grocerySentences = [
    "Where can I find the bread?",
    "Do you have any fresh produce?",
    "Is this on sale?",
    "Do you have any organic options?",
    "Where's the dairy section?",
    "Can I get a bag, please?",
    "How much is this?",
    "Do you have gluten-free products?",
    "Can I use my coupon here?",
    "Where are the canned goods?",
    "Do you sell soy milk?",
    "Is this item in stock?",
    "Do you have any more of this in the back?",
    "Can I return this if it’s faulty?",
    "Where's the meat section?",
    "Can I get a price check on this?",
    "Do you sell international foods?",
    "Where's the frozen food section?",
    "Are these eggs free-range?",
    "Where can I find baby products?",
    "Do you have a loyalty program?",
    "Can you help me find this item?",
    "Where are the cleaning supplies?",
    "Do you have any vegan options?",
    "Where can I weigh my produce?",
    "Is this product local?",
    "Where are the snacks?",
    "Do you have any non-dairy ice cream?",
    "Can I pay with my phone?",
    "Do you have any more of this brand?",
    "Where can I find spices?",
    "Is there a discount for bulk purchases?",
    "Do you have any low-sodium products?",
    "Where's the bakery section?",
    "Are these apples fresh?",
    "Where can I find pet food?",
    "Do you sell bottled water?",
    "Is this gluten-free?",
    "Where are the checkout counters?",
    "Do you have a restroom?",
    "Can I get this gift-wrapped?",
    "Where's the customer service desk?",
    "Can I use my own bags?",
    "Do you have any sugar-free options?",
    "Are these on special?",
    "Where can I find kitchenware?",
    "Do you sell flowers?",
    "Can I get some help here?",
    "Where's the seafood section?",
    "Do you have a pharmacy?"
]
